### ISSUE TITLE
TODO before RoHOW 2022

### ISSUE THREAD

**Issue by h3ndrk** [HULKs/mopad#43]
# 2022-10-29

- [x] editing while other peoples edit (focus gets lost) **CANNOT REPRODUCE**
- [x] enter press should blur, tab may select the next box
- [x] clientside validation duration
- [x] empty description
- [x] auto login
- [x] username field is not detected by KeePass
- [x] Add logout and footer when logged in

# 2022-11-16

- [x] Long titles do not wrap
- [x] Enter does not work in description
- [x] Creating new talk defocus'es
- [x] Failed login does not create an alert
- [x] Make footer links smaller
- [x] Noob/nerd counts twice sometimes (relogin increases counts)
